---
title: "Economic-Pandemic"
description: |
  COVID-19 crisis in Peru.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r libraries}
# remotes::install_github('htmlwidgets/sparkline')

library(readr)
library(tidyverse)
library(ggplot2)
library(plotly)
library(lubridate)
library(sparkline)
library(DT)
library(formattable)
library(scales)

data <- readr::read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv') %>% 
               filter(location == "Peru")
```

```{r}
peru <- data %>% select(location, date, new_cases, positive_rate, new_deaths, new_tests,
                        new_vaccinations, people_vaccinated, people_fully_vaccinated) %>%
  mutate(date = ymd(date),
         day = day(date),
         month = month(date),
         year = year(date))
```


```{r}
tab1<-  peru %>%
  mutate(quaters = quarter(date, with_year = TRUE)) %>% 
  group_by(quaters) %>%
  summarise("Tests" = sum(new_tests, na.rm = TRUE),
            "Positive Cases" = sum(new_cases, na.rm = TRUE),
            "Deaths" = sum(new_deaths, na.rm = TRUE)) %>%
  pivot_longer(cols = -quaters,
               names_to = "Variables",
               values_to = "value")%>%
  pivot_wider(names_from = Variables,
              values_from = value) %>%
  rename(Quaters = quaters)

   tab1 %>% 
  select(Quaters, Tests, 'Positive Cases', Deaths) %>% 
  as.data.frame() %>%  
  formattable(list(area(col = 4) ~ color_tile( "#3CB371", "#CD5C5C"))) #Higher value and Lower value

```
