---
title: "Vaccination"
description: |
  Understanding about COVID-19 vaccination in Peru.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r libraries}
# remotes::install_github('htmlwidgets/sparkline')

library(readr)
library(tidyverse)
library(ggplot2)
library(plotly)
library(lubridate)
library(sparkline)
library(DT)
library(formattable)
library(scales)

data <- readr::read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv') %>% 
               filter(location == "Peru")
```

```{r}
peru <- data %>% select(location, date, new_cases, positive_rate, new_deaths, new_tests,
                        new_vaccinations, people_vaccinated, people_fully_vaccinated) %>%
  mutate(date = ymd(date),
         day = day(date),
         month = month(date),
         year = year(date))
```


```{r}

peru %>%
  group_by(month) %>% filter(year == 2021) %>%
  mutate(month = month(date, label = TRUE)) %>%
  summarise("Vaccination" = sum(new_vaccinations, na.rm = TRUE),
            "Timeline" = spk_chr(new_vaccinations, type ="line"),
            "Partially Vaccinated" = sum(people_vaccinated, na.rm = TRUE),
            "Fully Vaccinated" = sum(people_fully_vaccinated, na.rm = TRUE),
            "Distribution" = spk_chr(people_fully_vaccinated, type ="box"))%>%
  rename(Month = month)%>%
  datatable(escape = FALSE, 
            ,caption = htmltools::tags$caption( style = 'caption-side: top; 
                                                text-align: center;  color:black; font-size:120% ;',
                                                'Vaccination Rate 2021'),
            options = c (list(pageLength = 10 ))) %>%
  spk_add_deps()


```
